portfolio:
  max_drawdown: 0.1
  max_positions: 5
position_sizing:
  confidence_scaling: true
  max_position_pct: 0.02
stop_loss:
  method: percentage
  value: 0.01
take_profit:
  method: percentage
  value: 0.02
